# Generated by Django 5.2.8 on 2025-11-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_contoler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pice',
            field=models.CharField(default='0 som', max_length=30),
        ),
    ]
